[package]
name = "pi-cluster"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
strum = "0.21.0"
strum_macros = "0.21"
tempfile = "3.2.0"
