name: Release
on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: clusterctl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}